//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Walker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Walker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Tests url=&quot;http://application_url/&quot;&gt;
        ///    &lt;Test name=&quot;Utworzenie obiektu&quot;&gt;
        ///        &lt;Login userName=&quot;administrator&quot; password=&quot;abc&quot; /&gt;
        ///        &lt;NavigateDetails className=&quot;Incident&quot; /&gt;
        ///        &lt;!-- ... --&gt;
        ///        &lt;Assert value=&quot;abc&quot; eq=&quot;abc&quot; /&gt;
        ///    &lt;/Test&gt;
        ///    
        ///    &lt;Test name=&quot;Logowanie do aplikacji&quot;&gt;
        ///        &lt;Login userName=&quot;administrator&quot; password=&quot;abc&quot; /&gt;
        ///    &lt;/Test&gt;
        ///&lt;/Tests&gt;.
        /// </summary>
        internal static string example {
            get {
                return ResourceManager.GetString("example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weryfikacja wartości.
        /// </summary>
        internal static string Method_Assert {
            get {
                return ResourceManager.GetString("Method_Assert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmienia bazowy url aplikacji, umożliwia np. przełączenie aplikacji.
        /// </summary>
        internal static string Method_BaseUrl {
            get {
                return ResourceManager.GetString("Method_BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawia wymiary przeglądarki (w pikselach).
        /// </summary>
        internal static string Method_BrowserSize {
            get {
                return ResourceManager.GetString("Method_BrowserSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przyciśnięcie przycisku.
        /// </summary>
        internal static string Method_ClickButton {
            get {
                return ResourceManager.GetString("Method_ClickButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etykieta przycisku.
        /// </summary>
        internal static string Method_ClickButton_label {
            get {
                return ResourceManager.GetString("Method_ClickButton_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliknięcie w komórkę na liście.
        /// </summary>
        internal static string Method_ClickList {
            get {
                return ResourceManager.GetString("Method_ClickList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa kolumny w którą ma nastąpić kliknięcie, domyślnie pierwsza..
        /// </summary>
        internal static string Method_ClickList_column {
            get {
                return ResourceManager.GetString("Method_ClickList_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kryteria wyboru rekordu, w postaci &lt;nazwa_kolumny&gt;:&lt;wartość&gt;[;...].
        /// </summary>
        internal static string Method_ClickList_criteria {
            get {
                return ResourceManager.GetString("Method_ClickList_criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etykieta listy lub #&lt;id_listy&gt;.
        /// </summary>
        internal static string Method_ClickList_list {
            get {
                return ResourceManager.GetString("Method_ClickList_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba elementów na liście.
        /// </summary>
        internal static string Method_CountList {
            get {
                return ResourceManager.GetString("Method_CountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etykieta listy lub #&lt;id_listy&gt;.
        /// </summary>
        internal static string Method_CountList_list {
            get {
                return ResourceManager.GetString("Method_CountList_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sformatowanie daty (format zgodny z .NET).
        /// </summary>
        internal static string Method_Date {
            get {
                return ResourceManager.GetString("Method_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobranie wartości z pola.
        /// </summary>
        internal static string Method_Get {
            get {
                return ResourceManager.GetString("Method_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa pola (etykieta) lub #&lt;id_pola&gt;.
        /// </summary>
        internal static string Method_Get_field {
            get {
                return ResourceManager.GetString("Method_Get_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobranie wartości z komórki na liście.
        /// </summary>
        internal static string Method_GetCell {
            get {
                return ResourceManager.GetString("Method_GetCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa kolumny z której ma być pobrana wartość.
        /// </summary>
        internal static string Method_GetCell_column {
            get {
                return ResourceManager.GetString("Method_GetCell_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kryteria wyboru rekordu, w postaci &lt;nazwa_kolumny&gt;:&lt;wartość&gt;[;...].
        /// </summary>
        internal static string Method_GetCell_criteria {
            get {
                return ResourceManager.GetString("Method_GetCell_criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etykieta listy lub #&lt;id_listy&gt;.
        /// </summary>
        internal static string Method_GetCell_list {
            get {
                return ResourceManager.GetString("Method_GetCell_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie do aplikacji.
        /// </summary>
        internal static string Method_Login {
            get {
                return ResourceManager.GetString("Method_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło użytkownika.
        /// </summary>
        internal static string Method_Login_password {
            get {
                return ResourceManager.GetString("Method_Login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika aplikacji.
        /// </summary>
        internal static string Method_Login_userName {
            get {
                return ResourceManager.GetString("Method_Login_userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wylogowanie się z aplikacji.
        /// </summary>
        internal static string Method_Logout {
            get {
                return ResourceManager.GetString("Method_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejście pod wskazany adres w ramach aplikacji.
        /// </summary>
        internal static string Method_Navigate {
            get {
                return ResourceManager.GetString("Method_Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejście do formularza szczegółów.
        /// </summary>
        internal static string Method_NavigateDetails {
            get {
                return ResourceManager.GetString("Method_NavigateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejście do listy (poprzez url w pasku adresu).
        /// </summary>
        internal static string Method_NavigateList {
            get {
                return ResourceManager.GetString("Method_NavigateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejście do formularza nowego obiektu, zwraca jego identyfikator.
        /// </summary>
        internal static string Method_NavigateNew {
            get {
                return ResourceManager.GetString("Method_NavigateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacja dodawania/odejmowania na zmiennych.
        /// </summary>
        internal static string Method_Op {
            get {
                return ResourceManager.GetString("Method_Op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis zrzutu ekranu przeglądarki.
        /// </summary>
        internal static string Method_Screenshot {
            get {
                return ResourceManager.GetString("Method_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybranie pozycji z menu.
        /// </summary>
        internal static string Method_SelectMenu {
            get {
                return ResourceManager.GetString("Method_SelectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka do menu, separowana znakiem &apos;/&apos;, np. &quot;Przejdź do.../Zgłoszenia&quot;..
        /// </summary>
        internal static string Method_SelectMenu_menu {
            get {
                return ResourceManager.GetString("Method_SelectMenu_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienie/wpisanie wartości w polu.
        /// </summary>
        internal static string Method_Set {
            get {
                return ResourceManager.GetString("Method_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa pola (etykieta) lub #&lt;id_pola&gt;.
        /// </summary>
        internal static string Method_Set_field {
            get {
                return ResourceManager.GetString("Method_Set_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość do ustawienia w polu.
        /// </summary>
        internal static string Method_Set_value {
            get {
                return ResourceManager.GetString("Method_Set_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wstrzymanie testu (czas w sekundach).
        /// </summary>
        internal static string Method_Sleep {
            get {
                return ResourceManager.GetString("Method_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przełączenie tab&apos;a na wskazany.
        /// </summary>
        internal static string Method_SwitchTab {
            get {
                return ResourceManager.GetString("Method_SwitchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etykieta zakładki.
        /// </summary>
        internal static string Method_SwitchTab_label {
            get {
                return ResourceManager.GetString("Method_SwitchTab_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienie wartości zmiennej (poprzez atrybut set).
        /// </summary>
        internal static string Method_Var {
            get {
                return ResourceManager.GetString("Method_Var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oczekiwanie na działanie aplikacji.
        /// </summary>
        internal static string Method_Wait {
            get {
                return ResourceManager.GetString("Method_Wait", resourceCulture);
            }
        }
    }
}
